//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地址位宽： 的本地化字符串。
        /// </summary>
        public static string Address_width {
            get {
                return ResourceManager.GetString("Address_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级信息 的本地化字符串。
        /// </summary>
        public static string Advanced_Info {
            get {
                return ResourceManager.GetString("Advanced_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU信息 的本地化字符串。
        /// </summary>
        public static string CPU_info {
            get {
                return ResourceManager.GetString("CPU_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启CPU使用率显示 的本地化字符串。
        /// </summary>
        public static string CPU_Ticker_enabled {
            get {
                return ResourceManager.GetString("CPU_Ticker_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU使用率 的本地化字符串。
        /// </summary>
        public static string CPU_Usage {
            get {
                return ResourceManager.GetString("CPU_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前使用率刷新时间间隔 的本地化字符串。
        /// </summary>
        public static string Current_refresh_time {
            get {
                return ResourceManager.GetString("Current_refresh_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前频率 的本地化字符串。
        /// </summary>
        public static string Current_speed {
            get {
                return ResourceManager.GetString("Current_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态码 的本地化字符串。
        /// </summary>
        public static string Current_status {
            get {
                return ResourceManager.GetString("Current_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU信息 的本地化字符串。
        /// </summary>
        public static string GPU_Info {
            get {
                return ResourceManager.GetString("GPU_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高时钟频率 的本地化字符串。
        /// </summary>
        public static string Max_clock_speed {
            get {
                return ResourceManager.GetString("Max_clock_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理器架构 的本地化字符串。
        /// </summary>
        public static string Processor_architecture {
            get {
                return ResourceManager.GetString("Processor_architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
    }
}
